/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsDate,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { EmployerWhereUniqueInput } from "../../employer/base/EmployerWhereUniqueInput";
import { ApplicationUpdateManyWithoutJobsInput } from "./ApplicationUpdateManyWithoutJobsInput";

@InputType()
class JobUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  location?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  salary?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  postedDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => EmployerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EmployerWhereUniqueInput)
  @IsOptional()
  @Field(() => EmployerWhereUniqueInput, {
    nullable: true,
  })
  employer?: EmployerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ApplicationUpdateManyWithoutJobsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationUpdateManyWithoutJobsInput)
  @IsOptional()
  @Field(() => ApplicationUpdateManyWithoutJobsInput, {
    nullable: true,
  })
  applications?: ApplicationUpdateManyWithoutJobsInput;
}

export { JobUpdateInput as JobUpdateInput };
