/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Internship } from "./Internship";
import { InternshipCountArgs } from "./InternshipCountArgs";
import { InternshipFindManyArgs } from "./InternshipFindManyArgs";
import { InternshipFindUniqueArgs } from "./InternshipFindUniqueArgs";
import { CreateInternshipArgs } from "./CreateInternshipArgs";
import { UpdateInternshipArgs } from "./UpdateInternshipArgs";
import { DeleteInternshipArgs } from "./DeleteInternshipArgs";
import { Employer } from "../../employer/base/Employer";
import { InternshipService } from "../internship.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Internship)
export class InternshipResolverBase {
  constructor(
    protected readonly service: InternshipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "read",
    possession: "any",
  })
  async _internshipsMeta(
    @graphql.Args() args: InternshipCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Internship])
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "read",
    possession: "any",
  })
  async internships(
    @graphql.Args() args: InternshipFindManyArgs
  ): Promise<Internship[]> {
    return this.service.internships(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Internship, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "read",
    possession: "own",
  })
  async internship(
    @graphql.Args() args: InternshipFindUniqueArgs
  ): Promise<Internship | null> {
    const result = await this.service.internship(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Internship)
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "create",
    possession: "any",
  })
  async createInternship(
    @graphql.Args() args: CreateInternshipArgs
  ): Promise<Internship> {
    return await this.service.createInternship({
      ...args,
      data: {
        ...args.data,

        employer: args.data.employer
          ? {
              connect: args.data.employer,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Internship)
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "update",
    possession: "any",
  })
  async updateInternship(
    @graphql.Args() args: UpdateInternshipArgs
  ): Promise<Internship | null> {
    try {
      return await this.service.updateInternship({
        ...args,
        data: {
          ...args.data,

          employer: args.data.employer
            ? {
                connect: args.data.employer,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Internship)
  @nestAccessControl.UseRoles({
    resource: "Internship",
    action: "delete",
    possession: "any",
  })
  async deleteInternship(
    @graphql.Args() args: DeleteInternshipArgs
  ): Promise<Internship | null> {
    try {
      return await this.service.deleteInternship(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Employer, {
    nullable: true,
    name: "employer",
  })
  @nestAccessControl.UseRoles({
    resource: "Employer",
    action: "read",
    possession: "any",
  })
  async getEmployer(
    @graphql.Parent() parent: Internship
  ): Promise<Employer | null> {
    const result = await this.service.getEmployer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
